spring:
  application:
    name: passkeys
  ssl:
    bundle:
      jks:
        localhost:
          key:
            password: changeit
          keystore:
            location: classpath:myapp-server-keystore.p12
            password: changeit
            type: PKCS12
server:
  port: 8443
  ssl:
    enabled: true
    bundle: localhost
  http2:
    enabled: true
  address: myapp.test
